### PR TITLE
Add command line parsing

### PR DESCRIPTION
**Pull request by Loki-Astari**
Add command line parsing.

Fix to https://github.com/GameTactic/CPP-Echo/issues/4

### CODE REVIEW

**Comment by NikoGrano** [comment]
Could it make more sense to have `include` folder where this would be put? Also might make sense when doing it also put websocketpp there? Any toughs?

**Comment by Loki-Astari** [comment]
Since websocketpp is a header only library it makes sense to use it as a sub-module.

If you are going that way I would suggest having a 3rd party include folder at the root.

````
CPP-Echo/
       include/
             websocketpp/         // sub-module
             ThorsHammer/         // sub-module
       src/
             main.cpp
````

I don't mind doing this adjust to the pull request.
Though I adding the `websocketpp` should come as its own pull request done separately.

**Comment by NikoGrano** [comment]
Yes, this is exactly what seems logical. Have you tested this PR with docker image. For some reason docker cloud CI doesnt run this....

I will be trying to fix it soonish...

**Comment by Loki-Astari** [comment]
Updated the commits to match the requested layout.
If this PR is accepted I will create another one for the websockets.


It runs in docker fine.

Are you building in docker?
After cloning the repository you need to fetch the submodules.

````
     git clone git@github.com:GameTactic/CPP-Echo.git
     cd CPP-Echo.git
     git submodule update --init --recursive
````

**Review by NikoGrano — CHANGES_REQUESTED** [review]
I opened PR to fix Docker issues. Please merge it and this PR can be merged.
https://github.com/Loki-Astari/CPP-Echo/pull/1

**Review by NikoGrano — APPROVED** [review]

**Pull request merged**
