### PR TITLE
Make sure we find dependencies

### PR DESCRIPTION
**Pull request by Loki-Astari**
Have a direct dependency on websocketpp.
    This is a header only library but make sure CMake finds this dependency correctly.

### CODE REVIEW

**Comment by Loki-Astari** [comment]
Hold on.

**Comment by NikoGrano** [comment]
How does this work. In docker file we do it by cloning the repository into specific folder, but for example locally I just install `websocketpp-dev` via package manager. Does this change affect where the library is loaded or?

**Comment by NikoGrano** [comment]
@Loki-Astari https://discord.gg/N4EQ9CW

**Comment by Loki-Astari** [comment]
This forces CMAKE to search the standard locations for websocketpp

I installed websocketpp via git and installed.

    > git clone git@github.com:zaphoyd/websocketpp.git
    > cd websocketpp
    > cmake .
    > make install

This placed websocketpp in `/usr/local/include/websocketpp`. Your existing makefile did not have `/usr/local/include` in the path. By using the above it forced CMAKE to attempt to find the headers and use them to build the server. So in the Makefile there is an extra `-I /use/local/include`.

When you install with your package installer it was probably placed in `/usr/include/websocketpp` but for a development environment I don't want websocketpp in /usr/include.

**Comment by Loki-Astari** [comment]
Can you re-open this one please.
I fixed a type and re-pushed.

**Comment by NikoGrano** [comment]
For some reason I'm not able to re-open this one. Please create new. :disappointed:

**Comment by Loki-Astari** [comment]
Will do

**Pull request closed without merging**
